name: codecov

on:
  push:
    branches:
      - develop

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Java
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0.2
        with:
          envkey_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          envkey_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          envkey_POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          envkey_MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          envkey_HOUR_EXPIRATION_TOKEN_EMAIL: ${{ secrets.HOUR_EXPIRATION_TOKEN_EMAIL }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_HOUR_EXPIRATION_TOKEN_JWT: ${{ secrets.HOUR_EXPIRATION_TOKEN_JWT }}
          envkey_HOUR_EXPIRATION_REFRESH_TOKEN_JWT: ${{ secrets.HOUR_EXPIRATION_REFRESH_TOKEN_JWT }}

      - name: Build and Test Main
        working-directory: .
        run: ./gradlew build

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.0-beta.3
        with:
          file: build/reports/jacoco/test/jacocoTestReport.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
