name: Develop branch workflow

on:
  push:
    branches:
      - feature/*
      - fix/*

jobs:
  build-feature-branch:
    name: Build feature branch and run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Java
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Set up environment variables and create .env file
        run: |
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> $GITHUB_ENV
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> $GITHUB_ENV
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV
          echo "POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }}" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "HOUR_EXPIRATION_TOKEN_EMAIL=${{ secrets.HOUR_EXPIRATION_TOKEN_EMAIL }}" >> $GITHUB_ENV

          echo "spring.config.import=optional:file:.env" >> $GITHUB_ENV

          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "HOUR_EXPIRATION_TOKEN_EMAIL=${{ secrets.HOUR_EXPIRATION_TOKEN_EMAIL }}" >> .env

      - name: Build and Test Main
        working-directory: .
        run: ./gradlew build