name: Develop branch workflow

on:
  push:
    branches:
      - feature/*
      - fix/*

jobs:
  build-feature-branch:
    name: Build feature branch and run unit tests
    runs-on: ubuntu-latest

    env:
      POSTGRES_HOST: ${{ secrets.env_POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.env_POSTGRES_PORT }}
      POSTGRES_DB: ${{ secrets.env_POSTGRES_DB }}
      POSTGRES_USERNAME: ${{ secrets.env_POSTGRES_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.env_POSTGRES_PASSWORD }}
      MAIL_USERNAME: ${{ secrets.env_MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.env_MAIL_PASSWORD }}
      HOUR_EXPIRATION_TOKEN_EMAIL: ${{ secrets.env_HOUR_EXPIRATION_TOKEN_EMAIL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Java
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Set up environment variables
        run: |
          echo "POSTGRES_HOST=${POSTGRES_HOST}" >> $GITHUB_ENV
          echo "POSTGRES_PORT=${POSTGRES_PORT}" >> $GITHUB_ENV
          echo "POSTGRES_DB=${POSTGRES_DB}" >> $GITHUB_ENV
          echo "POSTGRES_USERNAME=${POSTGRES_USERNAME}" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> $GITHUB_ENV
          echo "MAIL_USERNAME=${MAIL_USERNAME}" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=${MAIL_PASSWORD}" >> $GITHUB_ENV
          echo "HOUR_EXPIRATION_TOKEN_EMAIL=${HOUR_EXPIRATION_TOKEN_EMAIL}" >> $GITHUB_ENV

      - name: Build and Test Main
        working-directory: .
        run: ./gradlew build --scan