name: Develop branch workflow

on:
  push:
    branches:
      - feature/*
      - fix/*

jobs:
  build-feature-branch:
    name: Build feature branch and run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Java
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Print Java version
        run: java -version

      - name: Print Gradle version
        run: ./gradlew --version

      - name: Build and Test Main
        working-directory: .
        run: ./gradlew build --scan