name: Develop branch workflow

on:
  push:
    branches:
      - feature/*
      - fix/*

jobs:
  build-feature-branch:
    name: Build feature branch and run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Java
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0.2
        with:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          HOUR_EXPIRATION_TOKEN_EMAIL: ${{ secrets.HOUR_EXPIRATION_TOKEN_EMAIL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          HOUR_EXPIRATION_TOKEN_JWT: ${{ secrets.HOUR_EXPIRATION_TOKEN_JWT }}
          HOUR_EXPIRATION_REFRESH_TOKEN_JWT: ${{ secrets.HOUR_EXPIRATION_REFRESH_TOKEN_JWT }}

      - name: Build and Test Main
        working-directory: .
        run: ./gradlew build